#!/usr/bin/env python3
"""Tag Stash images/scenes with WD14 and store embeddings for character search.

  python tagger.py --kind images --limit 20 --dry-run   # preview
  python tagger.py --kind all                           # real run
"""
import argparse
import io
import re

import numpy as np
from PIL import Image

import config as cfg
from db import EmbDB
from stash_client import Stash, TagManager, chunks, tag_filter
from wd14 import WD14, display_name


def pretty(s):
    """Title-case words, including after '(' '/' '-': 'saber (fate)' -> 'Saber (Fate)'."""
    return re.sub(r"(^|[\s(/\-])([a-z])", lambda m: m.group(1) + m.group(2).upper(), s)


def char_parts(raw):
    """'saber_(fate)' -> ('Saber (Fate)', 'Fate'); 'hatsune_miku' -> ('Hatsune Miku', None)"""
    m = re.match(r"^.+_\(([^()]+)\)$", raw)
    series = pretty(m.group(1).replace("_", " ")) if m else None
    return pretty(raw.replace("_", " ")), series


def general_group(raw):
    if raw in cfg.COUNT_TAGS:
        return "Count"
    words = set(re.split(r"[_\s]+", raw))
    for group, keywords in cfg.GENERAL_GROUPS:
        if raw in keywords or words & keywords:
            return group
    return "Other"


class Hierarchy:
    def __init__(self, tm):
        r = cfg.ROOT_TAG
        self.tm = tm
        self.root = tm.get(r, description="Auto-generated by the WD14 tagger")
        self.marker = tm.get(cfg.MARKER_TAG, parents=[self.root])
        self.rating = tm.get(f"{r}: Rating", parents=[self.root])
        self.characters = tm.get(f"{r}: Characters", parents=[self.root])
        self.general = tm.get(f"{r}: General", parents=[self.root])
        self._groups = {}

    def group(self, name):
        if name not in self._groups:
            self._groups[name] = self.tm.get(f"{cfg.ROOT_TAG}: {name}", parents=[self.general])
        return self._groups[name]

    def tag_ids(self, labels):
        tm = self.tm
        ids = [self.marker, tm.get(f"rating:{labels['rating']}", parents=[self.rating])]
        for raw in labels["characters"]:
            name, series = char_parts(raw)
            parent = (tm.get(f"{cfg.SERIES_PREFIX}{series}", parents=[self.characters])
                      if series else self.characters)
            ids.append(tm.get(name, aliases=[raw], parents=[parent]))
        for raw in labels["general"]:
            ids.append(tm.get(display_name(raw), aliases=[raw],
                              parents=[self.group(general_group(raw))]))
        return list(dict.fromkeys(ids))


def untagged_ids(stash, kind, marker):
    filt = None if str(marker).startswith("dry-") else tag_filter(marker, "EXCLUDES")
    return stash.find_ids(kind, filt)


def map_path(path):
    for src, dst in cfg.PATH_MAP.items():
        if path.startswith(src):
            return dst + path[len(src):]
    return path


def apply(stash, db, kind, item_id, tag_ids, emb, labels, dry):
    if dry:
        print(f"  {kind} {item_id}: rating={labels['rating']} chars={labels['characters']} "
              f"general={labels['general'][:12]}{'...' if len(labels['general']) > 12 else ''}")
        return
    db.put(kind, item_id, cfg.MODEL_REPO, emb)
    stash.update_tags(kind, [item_id], tag_ids, "ADD")


def process_images(stash, H, model, db, limit, dry):
    ids = untagged_ids(stash, "image", H.marker)[:limit or None]
    print(f"{len(ids)} images to tag")
    done = skipped = 0
    for batch in chunks(ids, cfg.BATCH_SIZE):
        imgs, ok = [], []
        for iid in batch:
            try:
                info = stash.image_info(iid)
                im = Image.open(io.BytesIO(stash.get_bytes(info["paths"]["image"])))
                im.load()
                imgs.append(im)
                ok.append(iid)
            except Exception as e:
                skipped += 1
                print(f"  image {iid}: skipped ({e})")
        if not imgs:
            continue
        probs, embs = model.predict(imgs)
        for iid, p, e in zip(ok, probs, embs):
            labels = model.labels_for_image(p, cfg.GENERAL_THRESHOLD, cfg.CHARACTER_THRESHOLD)
            try:
                apply(stash, db, "image", iid, H.tag_ids(labels), e, labels, dry)
                done += 1
            except Exception as ex:
                skipped += 1
                print(f"  image {iid}: update failed ({ex})")
        db.commit()
        print(f"images: {done}/{len(ids)} tagged, {skipped} skipped")


def sample_frames(path, duration):
    import cv2
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        raise IOError(f"cannot open {path}")
    if not duration:
        fps = cap.get(cv2.CAP_PROP_FPS) or 0
        duration = (cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0) / fps if fps else 0
    count = max(1, min(cfg.SCENE_MAX_FRAMES, int(duration // cfg.SCENE_FRAME_INTERVAL)))
    start, end = duration * 0.02, duration * 0.98  # skip intros/black frames at the edges
    times = [start + (end - start) * (i + 0.5) / count for i in range(count)] if duration else [0]
    frames = []
    for t in times:
        cap.set(cv2.CAP_PROP_POS_MSEC, t * 1000)
        ok, frame = cap.read()
        if ok:
            frames.append(Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)))
    cap.release()
    return frames


def process_scenes(stash, H, model, db, limit, dry):
    ids = untagged_ids(stash, "scene", H.marker)[:limit or None]
    print(f"{len(ids)} scenes to tag")
    done = skipped = 0
    for sid in ids:
        try:
            files = stash.scene_info(sid)["files"]
            if not files:
                raise ValueError("no file")
            frames = sample_frames(map_path(files[0]["path"]), files[0].get("duration"))
            if not frames:
                raise ValueError("no frames decoded")
            P, E = zip(*(model.predict(ch) for ch in chunks(frames, cfg.BATCH_SIZE)))
            P, E = np.concatenate(P), np.concatenate(E)
            labels = model.labels_for_frames(
                P, cfg.GENERAL_THRESHOLD, cfg.CHARACTER_THRESHOLD,
                cfg.SCENE_GENERAL_MIN_FRACTION, cfg.SCENE_CHARACTER_MIN_FRACTION,
                cfg.SCENE_RATING_MIN_FRACTION)
            emb = E.mean(axis=0)
            emb /= np.linalg.norm(emb) + 1e-8
            apply(stash, db, "scene", sid, H.tag_ids(labels), emb, labels, dry)
            db.commit()
            done += 1
        except Exception as e:
            skipped += 1
            print(f"  scene {sid}: skipped ({e})")
        print(f"scenes: {done}/{len(ids)} tagged, {skipped} skipped")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--kind", choices=["images", "scenes", "all"], default="images")
    ap.add_argument("--limit", type=int, default=0, help="max items per kind (0 = all)")
    ap.add_argument("--dry-run", action="store_true", help="print tags, write nothing")
    a = ap.parse_args()

    stash = Stash(cfg.STASH_URL, cfg.STASH_API_KEY)
    tm = TagManager(stash, dry_run=a.dry_run)
    H = Hierarchy(tm)
    print(f"Loading {cfg.MODEL_REPO} ...")
    model = WD14(cfg.MODEL_REPO, cfg.MODEL_REVISION, cfg.DEVICE)
    db = EmbDB(cfg.DB_PATH)

    if a.kind in ("images", "all"):
        process_images(stash, H, model, db, a.limit, a.dry_run)
    if a.kind in ("scenes", "all"):
        process_scenes(stash, H, model, db, a.limit, a.dry_run)


if __name__ == "__main__":
    main()
